version: '3.8'

services:
  comfyui-instantid:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comfyui-instantid
    ports:
      - "6000:6000"  # ComfyUI interface
      - "8000:8000"  # FastAPI application
    volumes:
      - comfyui-outputs:/app/ComfyUI/output  # Persist generated images
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

volumes:
  comfyui-outputs:
    name: comfyui-outputs